//main
export const START_REQUEST = 'START_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

//driver
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS';
export const GET_DRIVERS_FAIL = 'GET_DRIVERS_FAIL';
export const GET_DRIVER_SUCCESS = 'GET_DRIVERS_SUCCESS';
export const GET_DRIVER_FAIL = 'GET_DRIVERS_FAIL';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';
export const DELETE_DRIVER_FAIL = 'DELETE_DRIVER_FAIL';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';
export const UPDATE_DRIVER_FAIL = 'UPDATE_DRIVER_FAIL';

//reviews
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
export const EDIT_REVIEW_FAIL = 'EDIT_REVIEW_FAIL';

//rider
export const GET_RIDERS_SUCCESS = 'GET_RIDER_SUCCESS';
export const GET_RIDERS_FAIL = 'GET_RIDER_FAIL';
export const GET_RIDER_SUCCESS = 'GET_RIDER_SUCCESS';
export const GET_RIDER_FAIL = 'GET_RIDER_FAIL';
export const DELETE_RIDER_SUCCESS = 'DELETE_RIDER_SUCCESS';
export const DELETE_RIDER_FAIL = 'DELETE_RIDER_FAIL';
export const UPDATE_RIDER_SUCCESS = 'UPDATE_RIDER_SUCCESS';
export const UPDATE_RIDER_FAIL = 'UPDATE_RIDER_FAIL';
